[김택향] 가게 등록 view 구현
wecode-bootcamp-korea/18-2nd-mukbang-backend pull request #3
Opened 2021-04-02 00:50 UTC by Taekhyang

## 수정 사항 간략한 한줄 요약
- 가게 등록 view 구현
		 
## 수정 사항들 자세한 내용
- Enum class 를 활용하여, 정해진 input 값만 받도록 함
- transaction 으로 atomic 하게 데이터가 save 되도록 함 

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-02 02:38 UTC, ulfrid requested changes
생각해보시고 유닛테스트 부탁드립니다~!

2021-04-02 02:38 UTC, ulfrid commented on store/views.py
> +                category, _ = Category.objects.get_or_create(name=category_name)
category의 이름은 이미 한정적 비교를 하고, 리스트에 존재하지 않으면 에러를 리턴하는데, 
category를 가져올때는 category를 가져오거나 없으면 만드는 메서드를 사용하는게 논리적으로 맞는건지 생각이 드네요.
카테고리를 비교하기 위해 고정 값을 사용중이라면, 결국 모델에 데이터가 이미 준비되어 있는 방식의 설계라고 생각드는데,
그게 아니고, 일단 논리적 제한을 걸어두고, 저 기준으로 생성될때 데이터를 등록하는 비즈니스 로직이라면 이해는 갑니다.
여기서 어떤 방식이 효율적이다 논할 수는 없겠지만, 일단 결국 모델에 확정 데이터를 두고 모델 통해 비교하는게 전체 메모리 총량 부분에서는 더 효율적이라 생각됩니다.

이러한 시도를 하신 부분에 대해서는 칭찬 드립니다. 근데 로직만 처음 봐서는 효율적으로 다가오지는 않네요. 또한  만드신 Exception도 정말 Exception으로 처리해야만할까에 대해 고민해보는건 어떨까요?

2021-04-02 03:06 UTC, Taekhyang commented on store/views.py
> +                category, _ = Category.objects.get_or_create(name=category_name)
모델에 category 데이터를 미리 등록해놓고 모델을 통해 비교하는 방법이,
불필요한 enum 클래스를 만들지 않아도 돼서 더 나은것같습니다.

그렇다면 말씀해주신 내용이 OpenStatus enum 클래스에도 해당되는 이야기인가요 ?

또한 예외처리에 관해서는,
raise <exception_name> 으로 처리하지 않고 그냥 return 으로 처리해버리면
transaction.atomic() 이 작동을 안해서 db에 데이터가 들어가버려서
에러를 발생시키는 방법으로 진행했습니다. 그래서 atomic 하게 처리하는
transaction 메소드에대해서 여러개 보았지만, 이해가 잘 되지 않아서 
그냥 transaction.atomic() 을 로직 전체에 걸고 exception 을 raise 하는 방법을 사용했습니다.

2021-04-02 07:25 UTC, ulfrid commented on store/views.py
> +                category, _ = Category.objects.get_or_create(name=category_name)
transaction 스테이터스를 관리하고 싶어서라면~ 
https://docs.djangoproject.com/en/3.1/topics/db/transactions/#django.db.transaction.clean_savepoints 
이방법은 어떨까요?

2021-04-02 08:00 UTC, ulfrid commented on store/views.py
> +                category, _ = Category.objects.get_or_create(name=category_name)
OrderStatus도 마찬가지입니다.

2021-04-05 02:08 UTC, ulfrid commented
생각하시는 것보다 크게 무리 없어 보입니다. 택향님~! LGTM 👍

2021-04-05 02:08 UTC, merged

2021-04-05 02:29 UTC, Taekhyang commented
> 생각하시는 것보다 크게 무리 없어 보입니다. 택향님~! LGTM

감사합니다 ㅎㅎ