[김택향] 좌표 값 기준 가게정보 표시 & 가게 세부정보 표시
wecode-bootcamp-korea/18-2nd-mukbang-backend pull request #4
Opened 2021-04-05 03:28 UTC by Taekhyang

>wecode PR message template 및 체크 리스트 입니다. 

## 수정 사항 간략한 한줄 요약
-  좌표 값을 받으면 가게정보 표시
- 가게정보 디테일 표시
		 
## 수정 사항들 자세한 내용
- 위도, 경도, 축척, pixel 값 받으면 map 의 boundary 를 계산해서, 그 안에있는 가게 정보들 모두 표시
- 가게 정보 디테일 store_id 받으면 표시
- 지하철역과 상점 간의 거리 haversine 모듈통해 계산해서 표시
- geopy 모듈을 통해 (위도, 경도 값) + (미터) --> (위도, 경도)로 환산
- 같은 view 내에서 offset, limit 옵션을 받으면 페이지네이션 가능, 없으면 전체 가게 보여줌
- 카테고리, 가격 범위로 필터링 기능 추가
- unittest 는 아직 하는중입니다. 

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-05 08:43 UTC, ulfrid requested changes
택향님 잘하셨는데, 정말 사소한건데, lon보다는 longitude 줄일때는 lng로 많이 합니다.
또한 아까 대화나눈후 클래스 메소드와 정적 메소드의 결정적 차이는 상속시에 정적 메소드는 부모 클래스의 속성만 접근 하는 반면, 클래스 메소드는 자식클래스의 속성도 접근 가능하다는 차이가 있다고 하네요. 어쨋든 정적 메소드는 별로 쓸일이 없어서 저도 활용가치는 잘 모르겠습니다~ ㅎㅎ
위의 사항만 변경해주시면 머지할께요.

2021-04-05 10:46 UTC, Taekhyang commented
> 택향님 잘하셨는데, 정말 사소한건데, lon보다는 longitude 줄일때는 lng로 많이 합니다.
> 또한 아까 대화나눈후 클래스 메소드와 정적 메소드의 결정적 차이는 상속시에 정적 메소드는 부모 클래스의 속성만 접근 하는 반면, 클래스 메소드는 자식클래스의 속성도 접근 가능하다는 차이가 있다고 하네요. 어쨋든 정적 메소드는 별로 쓸일이 없어서 저도 활용가치는 잘 모르겠습니다~ ㅎㅎ
> 위의 사항만 변경해주시면 머지할께요.

차이 알려주셔서 감사합니다 ! 지적해주신 변수이름도 수정 및 unittest 도 테스트 완료했습니다.

2021-04-06 00:36 UTC, ulfrid requested changes
확인 바랍니다~!

2021-04-06 00:36 UTC, ulfrid commented on store/views.py
> +
전체적인 쿼리 최적화요소중 하나인 select_related, prefetch_related 사용이 필요해보이는데, 일단 이부분은 settings에 로깅을 활성화 하면 쿼리가 찍히는 부분을 확인 할 수 있습니다. 

```
LOGGING = {
    'disable_existing_loggers': False,
    'version': 1,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
        },
    },
    'loggers': {
        'django.db.backends': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}
```

2021-04-06 02:27 UTC, Taekhyang commented on store/views.py
> +
적용해보겠습니다 !

2021-04-06 13:11 UTC, ulfrid requested changes
확인 바랍니다. 쿼리 최적화는 잘하셨습니다.

2021-04-06 13:11 UTC, ulfrid commented on mukbang/settings.py
> +}
로거는 사용할때만 적용하고 끝나면 제거해주세요 ^^

2021-04-06 13:11 UTC, ulfrid commented on store/views.py
> +        return len(store_obj.review_set.all())
이건 지금 보니 오히려 이렇게 양쪽에서 쓰일거면 그냥 상단에 별도 클래스 메소드로 뽑거나 그냥 펑션으로 뽑는게 나을것 같네요.

2021-04-07 02:25 UTC, Taekhyang commented on mukbang/settings.py
> +}
네 제거했습니다 !

2021-04-07 02:25 UTC, Taekhyang commented on store/views.py
> +        return len(store_obj.review_set.all())
말씀 주신대로 상단에 별도 클래스를 만들었습니다.

2021-04-07 02:46 UTC, ulfrid commented
LGTM 👍

2021-04-07 02:46 UTC, merged