ADD: signup func.
wecode-bootcamp-korea/18-2nd-mukbang-backend pull request #5
Opened 2021-04-05 04:31 UTC by hlrrr

## 수정 사항 간략한 한줄 요약
- 문자인증을 통한 일반 회원가입 기능
		 
## 수정 사항들 자세한 내용
- 네이버 문자전송 api를 활용한 문자인증 
1. 사용자 전화번호 입력시 인증 코드 문자 전송 및 암호와된 인증코드 프론트에 전달
2. 사용자가 입력한 인증코드 암호화하여 대조
3. 인증 성공 시만료시간이 설정 된 JWT 전달
4. JWT 확인하여 회원가입 완료
 
-유닛 테스트 작성중...

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [X] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [X] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [X] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [X] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [X] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-05 09:05 UTC, ulfrid requested changes
유닛 테스트 업데이트 해주시고, 수정사항 확인 바랍니다

2021-04-05 09:05 UTC, devops-andrew commented on .vscode/settings.json
> +}
요건 포함되면 안되겠죠~ 제거 부탁드립니다.

2021-04-05 09:05 UTC, devops-andrew commented on mukbang/urls.py
>  """
주석도 제거해주세요.

2021-04-05 09:05 UTC, devops-andrew commented on user/views.py
> +import datetime
```suggestion
import json, bcrypt, re
import hashlib, hmac, base64
import requests, time, random
import jwt, datetime
```
이정도면 3개씩 해주죠~

2021-04-05 09:05 UTC, ulfrid commented on user/views.py
> +            password_regex = re.compile(r'^(?=.*[!-/:-@])(?!.*[ㄱ-ㅣ가-힣]).{8,20}$')
이런 정규식 항목은 상수화 해서 my_settings.py로 빼서 임포트 합시다~!

2021-04-05 09:05 UTC, ulfrid commented on user/views.py
> +
의미없는 빈줄 주지 않도록 해주세요~!

2021-04-05 09:05 UTC, ulfrid commented on user/views.py
> +                return JsonResponse({'message': 'error_email_exists'}, status=401)
```suggestion
                return JsonResponse({'message': 'ERROR_EMAIL_EXISTS'}, status=401)
```
우리가 status 코드로 이미 설명이 되는 에러에  메세지를 주는 이유는 같은  status 코드에서도 분별력있는 판단이 되도록 하는 것 입니다. 다만 이를 대문자 및 단어 구분시 '_'로 이어주는 컨벤션으로 에러 메세지도 하나의 코드로서 관리하려고 안내 드린겁니다~! 그러므로 에러 메세지는 간결하고 메세지 코드로서 강조드린 컨벤션대로 작성 부탁드립니다!

2021-04-06 00:33 UTC, hlrrr commented on mukbang/urls.py
>  """
수정하겠습니다!

2021-04-06 00:33 UTC, hlrrr commented on .vscode/settings.json
> +}
수정하겠습니다!

2021-04-06 00:34 UTC, hlrrr commented on user/views.py
> +import datetime
수정하겠습니다!

2021-04-06 00:36 UTC, hlrrr commented on user/views.py
> +            password_regex = re.compile(r'^(?=.*[!-/:-@])(?!.*[ㄱ-ㅣ가-힣]).{8,20}$')
수정하겠습니다!

2021-04-06 00:43 UTC, hlrrr commented on user/views.py
> +
알겠습니다~

2021-04-06 00:44 UTC, hlrrr commented on user/views.py
> +                return JsonResponse({'message': 'error_email_exists'}, status=401)
수정하겠습니다.

2021-04-07 02:45 UTC, ulfrid requested changes
확인 바랍니다~!

2021-04-07 02:45 UTC, ulfrid commented on user/validator.py
> +#     return Wrapper
이런 흔적이 main에 병합되어서는 안되겠죠~!

2021-04-07 02:45 UTC, ulfrid commented on user/views.py
> +                response          = requests.post(sms_service_url, headers=headers, data=json.dumps(body))
requests로 send할때는 항상 적절한 timeout을 걸어주세요. 아니면 문제가 발생했을때 무한정 대기하게 됩니다.

2021-04-07 02:45 UTC, ulfrid commented on user/views.py
> +                    'x-ncp-apigw-signature-v2':SMSCodeRequestView.make_signature()
```suggestion
                    'x-ncp-apigw-signature-v2':self.make_signature()
```
이렇게 해도 되지 않을까요?

2021-04-07 02:45 UTC, ulfrid commented on user/tests.py
> +        unittest.main()
굳이 명시 안하셔도 될것 같아요 제거 부탁드립니다.

2021-04-07 02:45 UTC, ulfrid commented on user/tests.py
> +        unittest.main()
다른 부분도 제거해주세요

2021-04-07 02:45 UTC, ulfrid commented on .vscode/settings.json
> +}
여전히 포함되어 있습니다. git rm --cached 로 삭제 하셔야 합니다.

2021-04-07 08:25 UTC, hlrrr commented on user/validator.py
> +#     return Wrapper
삭제하였습니다.

2021-04-07 08:26 UTC, hlrrr commented on user/views.py
> +                response          = requests.post(sms_service_url, headers=headers, data=json.dumps(body))
timeout_seconds 추가하였습니다.

2021-04-07 08:30 UTC, hlrrr commented on user/views.py
> +                    'x-ncp-apigw-signature-v2':SMSCodeRequestView.make_signature()
self 인자 추가하여 수정하였습니다.

2021-04-07 08:31 UTC, hlrrr commented on user/tests.py
> +        unittest.main()
모두 제거하였습니다.

2021-04-07 10:14 UTC, ulfrid commented
LGTM 👍

2021-04-07 10:14 UTC, merged